### ISSUE TITLE
What is the proper way to resize gauges?

### ISSUE THREAD

**Issue by christian-nils** [swina/rockiot-ui#1]
Hi,

Very nice components. I am using the vertical linear gauges for a Vue project. I would like to have smaller gauges than the smallest available option (i.e., _sm_). Is there a proper way to change the size? Let's say that I would like to have a height for my gauge's svg of 40 px, is there a prop I could use?

Thanks in advance!

**Comment by swina** [comment]
At the moment for the linear gauge there is an issue about the height and width (this is because in case of negative values I have to update the right calculation).
But since is a web component you can make a little workaround with plain CSS attribute.
Add a simple CSS (with style or with a new class) to the component 

`transform: scale(.4);` 

Adjust the value to fix for your needs. You can disable the scale indicators as well setting scale="0".
I am going to update the component next days in order to fix the size settings working properly. Working on it. Sorry for the issue.

**Comment by christian-nils** [comment]
Thanks @swina, no needs of apologizes, I am so grateful these components are made available, this is a very small issue ;)
I modified a bit the rockiot.linear.vertical.svg.vue component to expose the svgwidth and svgheight data as props. It solved my issue

**Comment by swina** [comment]
You can make a merge to the original I will package for npm.
